### ISSUE TITLE
No oculta clave de c/ jugador tras ingresar el nombre de los jugadores

### ISSUE THREAD

**Issue by beelanselm** [federicofranco97/uno_game#17]
Proyecto: UNO
Versión: 1
Plataforma: PC - Windows 64 bits
Título: No oculta clave de c/ jugador tras ingresar el nombre de los jugadores
Descripción: Tras crear una nueva partida y generar dos nuevos jugadores, la clave de cada jugador que uno ingresa es visible para el otro jugador. Deberia estar oculta

**Comment by federicofranco97** [comment]
Not an error: Esta diseñado para que cuando se defina la contraseña del jugador pueda ver que esta escribiendo para evitar un error de tipeo y que cuando empieza el juego no pueda acceder a su usuario.
