### ISSUE TITLE
No hay limite en cantidad de cartas para levantar

### ISSUE THREAD

**Issue by beelanselm** [federicofranco97/uno_game#18]
Proyecto: UNO
Versión: 1
Plataforma: PC - Windows 64 bits
Título: No hay limite en cantidad de cartas para levantar
Descripción: En el turno del jugador, se deberia poder levantar una sola carta. Te permite levantar todas las cartas hasta que se llena el tablero

**Comment by federicofranco97** [comment]
Hay muchas corrientes de reglas del UNO , nosotros nos basamos en la que establece que se pueden levantar las cartas que el jugador desee, siempre dentro del limite de cartas que se establece en la interfaz. 
(Una vez que se llena la vista de cartas, el juego no permite levantar mas).
