### ISSUE TITLE
Fondo confuso con las cartas

### ISSUE THREAD

**Issue by franciscoMigliardi24** [federicofranco97/uno_game#19]
Proyecto: UNO
Versión: 1
Plataforma: PC - Windows 64 bits
Título: Fondo confuso con las cartas
Descripción: el fondo de cartas de UNO causa dificultad al ver las cartas de UNO que estan en frente

**Comment by federicofranco97** [comment]
Won't change las cartas tienen un borde blanco y son distinguibles del fondo que se ve pixelado. Se va a considerar que en proximas actualizaciones el fondo tenga mas opacidad
