### ISSUE TITLE
Flujo de usabilidad algo lento por pass

### ISSUE THREAD

**Issue by diegomoran777** [federicofranco97/uno_game#20]
Proyecto: Uno
Version: ?
Plataforma: Pc - Windows 10 64 -8 gb ram
Gravedad: trivial-min
Descripcion: El flujo de la usabilidad es lento por poner los pass- usabilidad 
Paso a paso: cuando cambia de jugador hay que poner la clave nuevamente
se abre el juego, se ingresan los jugadores y en el juego cuando cambia al proximo jugador pasa esto.
Tasa de reproduccion:100%

**Comment by federicofranco97** [comment]
Not an error. Estaba establecido en las consignas que cada vez que pase de turno le pida la contraseña al jugador que le toca para evitar malas intenciones.
