### ISSUE TITLE
Focus on text field

### ISSUE THREAD

**Issue by franciscoMigliardi24** [federicofranco97/uno_game#21]
Proyecto: UNO
Versión: 1
Plataforma: PC - Windows 64 bits
Título: Focus on text field (contraseña)
Descripción: para poner la contraseña hay que hacer click con el cursor todo el tiempo en el campo para ingresar la contraseña, se hace tedioso y repetitivo

**Comment by federicofranco97** [comment]
To be considered. En poximos updates.
