### ISSUE TITLE
No se puede salir de la ventana de ingresar clave

### ISSUE THREAD

**Issue by CacoRod** [federicofranco97/uno_game#22]
Proyecto: Uno
Version: 1.00
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: medio
Descripcion: la ventana de ingresar clave no puede cerrarse
Paso a paso: comienza una partida. al momento de ingresar una clave intenta cerrar el juego con los botones
Tasa de reproduccion:100%

**Comment by federicofranco97** [comment]
Not an error. Si aparece la ventana de ingresar clave es porque un jugador eligio una accion que causa que la ronda sigue por lo tanto no tiene porque haber una opción de salir del juego.
