### ISSUE TITLE
se pueden crear jugadores con el mismo nombre y la misma clave

### ISSUE THREAD

**Issue by CacoRod** [federicofranco97/uno_game#23]
Proyecto: Uno
Version: 1.00
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: medio
Descripcion: se pueden crear jugadores con el mismo nombre y la misma clave
Paso a paso: al comenzar un nuevo juego, dale el mismo nombre y clave a dos jugadores distintos
Tasa de reproduccion:100%

**Comment by federicofranco97** [comment]
Not an error. No hay ninguna regla que indique que los nombres de los jugadores no puedan repetirse. Al igual que con las claves
