### ISSUE TITLE
No contiene instrucciones de como jugar

### ISSUE THREAD

**Issue by CacoRod** [federicofranco97/uno_game#24]
Proyecto: Uno
Version: 1.00
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: trivial- min
Descripcion: el juego no incluye instrucciones
Paso a paso: al comenzar el juego no hay un menu de instrucciones
Tasa de reproduccion:100%

**Comment by federicofranco97** [comment]
Not required. No estaba en las instrucciones del proyecto que el juego incluya un manual.

**Comment by federicofranco97** [comment]
Not required. No estaba en las instrucciones del proyecto que el juego incluya un manual.
