### ISSUE TITLE
Al renaudar partida, en caso de arrepentirse, no se puede cerrar la ventana de clave

### ISSUE THREAD

**Issue by CacoRod** [federicofranco97/uno_game#25]
Proyecto: Uno
Version: 1
Plataforma: Pc - Windows 7 64b -8 gb ram
Gravedad: trivial- min
Descripcion: al presionar renaudar partida, en caso de arrepentirse y querer comenzar una partida nueva, la unica manera es matando el proceso del programa por task manager
Tasa de reproduccion:100%

**Comment by federicofranco97** [comment]
Not an error. Si se pone reanudar partida esta implicito que se quiere reanudar el juego por lo tanto la clave del jugador de turno es requerida. Si se arrepiente y quiere cerrar dicho jugador debe salir del juego.
